language: r

warnings_are_errors: true

sudo: required

r_build_args: --compact-vignettes=both

#language: c
#
#sudo: required
#
#before_install:
#  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
#  - chmod 755 ./travis-tool.sh
#  - ./travis-tool.sh bootstrap
#
#install:
#  - ./travis-tool.sh install_deps
#
#script: ./travis-tool.sh run_tests
#
#after_failure:
#  - ./travis-tool.sh dump_logs
#
#env:
#  global:
#    - WARNINGS_ARE_ERRORS=1
#    - R_BUILD_ARGS=--no-build-vignettes --no-manual
#    - R_CHECK_ARGS=--no-build-vignettes --no-manual --as-cran

notifications:
  email:
    on_success: change
    on_failure: change
